# Config file for `air` live reloading
root = "."
tmp_dir = "tmp"


[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/web/"
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"
  exclude_dir = ["tmp"]
  include_ext = ["go", "tpl", "tmpl", "html", "gohtml"]
  exclude_file = []
  follow_symlink = true
  delay = 1000 # ms
[run]
  cmd = "powershell -File ./tmp/main.exe"
